/**
 * Turns an analyzed call into a Markdown report the user can keep.
 *
 * The Download Report button used to do nothing, which the vibe-coded-site
 * report calls out directly: a control that does not respond reads as unfinished
 * regardless of what is behind it. This makes it real.
 *
 * Everything written here comes from the stored analysis. Fields the call did
 * not state are omitted rather than filled with placeholders — the same rule the
 * interface follows.
 */

function section(title, lines) {
  const body = lines.filter(Boolean);
  return body.length ? [`## ${title}`, "", ...body, ""] : [];
}

function bullets(items) {
  return (items ?? []).filter(Boolean).map((i) => `- ${i}`);
}

export function buildReport(call) {
  const financials = call.financials ?? {};
  const outlook = call.outlook ?? {};
  const opening = call.opening ?? {};

  const figures = [
    ["Revenue", financials.revenue],
    ["Revenue growth", financials.revenue_growth],
    ["Net income", financials.net_income],
    ["Earnings per share", financials.eps],
    ["Gross margin", financials.gross_margin],
    ["Operating margin", financials.operating_margin],
    ["Free cash flow", financials.free_cash_flow],
    ["Cash position", financials.cash_position],
    ["Debt", financials.debt],
  ].filter(([, value]) => value);

  const lines = [
    `# ${call.company}${call.ticker ? ` (${call.ticker})` : ""}`,
    "",
    [call.quarter, call.date].filter(Boolean).join(" · ") || "Quarter not stated",
    "",
    "---",
    "",

    ...section("At a glance", [
      `- Management tone: ${call.sentiment}/100 (${call.sentimentLabel})`,
      `- Guidance: ${call.guidance}`,
      call.revenueOutlook ? `- Revenue outlook: ${call.revenueOutlook}` : "",
      `- Risks flagged: ${call.riskFlags ?? 0}`,
    ]),

    ...section(
      "How management framed the quarter",
      opening.ceo_summary ? [opening.ceo_summary] : [],
    ),

    ...section("What moved the numbers", bullets(opening.drivers)),

    ...section(
      "Stated figures",
      figures.length
        ? [
            "| Figure | Value |",
            "| --- | --- |",
            ...figures.map(([label, value]) => `| ${label} | ${value} |`),
          ]
        : [],
    ),

    ...section("Outlook", [
      outlook.next_quarter ? `**Next quarter.** ${outlook.next_quarter}` : "",
      outlook.full_year ? `**Full year.** ${outlook.full_year}` : "",
    ]),

    ...section("Challenges management raised", bullets(outlook.challenges)),

    ...section("Positives", bullets(call.takeaways?.bullish)),
    ...section("Negatives", bullets(call.takeaways?.bearish)),
    ...section("Risks", bullets(call.riskList)),

    ...section(
      "Question and answer",
      (call.qa ?? []).flatMap((x) => [
        `**${x.analyst || "Analyst"}${x.firm ? `, ${x.firm}` : ""}** — ${x.directness || "—"}`,
        "",
        `*Q.* ${x.question}`,
        "",
        `*A.* ${x.answered_by ? `${x.answered_by}: ` : ""}${x.answer}`,
        "",
      ]),
    ),

    ...section(
      "On the call",
      (call.speakers ?? []).map((s) => `- ${s.name}${s.role ? ` — ${s.role}` : ""}`),
    ),

    "---",
    "",
    "Generated by CallPal. Analysis is AI-generated from the call transcript and",
    "is not investment advice. Figures are only those management stated on the",
    "call; anything not said was left out rather than estimated.",
  ];

  return lines.join("\n");
}

/** Filename that sorts sensibly in a folder: ticker, then date. */
export function reportName(call) {
  const who = (call.ticker || call.company || "call")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

  return `callpal-${who}${call.date ? `-${call.date}` : ""}.md`;
}

export function downloadReport(call) {
  const blob = new Blob([buildReport(call)], {
    type: "text/markdown;charset=utf-8",
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = reportName(call);
  document.body.appendChild(link);
  link.click();
  link.remove();

  // Chrome keeps the blob alive until the object URL is released.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
